const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),C=require('./core.js');
process.env.TZ='Asia/Shanghai';
const now=Date.parse('2026-09-10T00:00:00Z'),base={...C.planDefaults(),action:'walk',at:'2026-09-11T20:30',minutes:20,confirmed:true};
const checks=[
 ['AI 请求必须包含原话和明确的自身状态',()=>{for(const invalid of [{need:'listen',capacity:'now'},{source:'话',need:'listen',capacity:''},{source:' ',need:'listen',capacity:'now'}])assert.throws(()=>C.parseAIRequest(invalid));}],
 ['原话和关系背景完整进入请求，不再被生成逻辑忽略',()=>{const input={source:C.examples.friend,background:'我们是室友，之前我急着给建议。',need:'listen',capacity:'now',minutes:20};const value=C.parseAIRequest(input);assert.equal(value.source,input.source);assert.equal(value.background,input.background);assert.equal(value.minutes,20);assert.throws(()=>C.parseAIRequest({...input,apiKey:'must-not-be-client-input'}));assert.throws(()=>C.parseAIRequest({...input,background:'字'.repeat(401)}));}],
 ['不同余力和独处请求保持原始约束',()=>{for(const capacity of Object.keys(C.capacities)){const value=C.parseAIRequest({source:C.examples.partner,need:'space',capacity,later:'今晚九点后'});assert.equal(value.need,'space');assert.equal(value.capacity,capacity);assert.equal(value.later,'今晚九点后');}}],
 ['模型返回必须含有正文和可核对依据，不用模板掩盖坏响应',()=>{assert.deepEqual(C.parseAIResult({reply:' 一句话 ',considerations:[' 一个依据 '],extra:'discard'}),{reply:'一句话',considerations:['一个依据']});for(const invalid of [{reply:'',considerations:['依据']},{reply:'正文',considerations:[]},{reply:'正文',considerations:['字'.repeat(241)]},{reply:'正文',considerations:'不是数组'}])assert.throws(()=>C.parseAIResult(invalid));assert.equal(C.reply,undefined);}],
 ['输入边界与枚举校验',()=>{const s=C.response({need:'diagnose',capacity:'always',source:'字'.repeat(1800),minutes:999});assert.equal(s.need,'unknown');assert.equal(s.capacity,'');assert.equal(s.source.length,1600);assert.equal(s.minutes,10);for(const bad of [{need:'listen',capacity:'now',source:'secret'},{need:'listen',capacity:'now',minutes:'10'},{need:'listen',capacity:'now',detail:'字'.repeat(201)},{need:'diagnose',capacity:'now'}])assert.throws(()=>C.parseReplyInput(bad));assert.equal(C.parseReplyInput({need:'listen',capacity:'now',minutes:20}).minutes,20);}],
 ['约定拒绝空安排、过去时间和无效日期',()=>{assert.ok(C.validatePlan(C.planDefaults(),now));assert.ok(C.validatePlan({...base,at:'2026-02-30T20:30'},now));assert.ok(C.validatePlan({...base,at:'2026-09-09T20:30'},now));assert.equal(C.validatePlan(base,now),'');assert.equal(C.startDate('2026-09-11T25:30'),null);assert.equal(C.startDate('2026-09-11'),null);}],
 ['改期后必须重新确认，不能保留完成状态',()=>{const changed=C.changePlan({...base,done:true},{at:'2026-09-12T20:30',confirmed:true});assert.equal(changed.confirmed,false);assert.equal(changed.done,false);assert.equal(base.confirmed,true);}],
 ['未确认、已完成或过期的约定不能导出日历',()=>{assert.throws(()=>C.calendar({...base,confirmed:false},'demo',now));assert.throws(()=>C.calendar({...base,done:true},'demo',now));assert.throws(()=>C.calendar(base,'demo',Date.parse('2026-09-12T00:00:00Z')));}],
 ['日历准确转换时区、持续时间，不携带昵称或邀请收件人',()=>{const text=C.calendar({...base,person:'不应外发的昵称'},'test-event',now);assert.ok(text.includes('DTSTART:20260911T123000Z'));assert.ok(text.includes('DTEND:20260911T125000Z'));assert.ok(text.endsWith('END:VCALENDAR\r\n'));for(const hidden of ['不应外发的昵称','ATTENDEE','ORGANIZER','VALARM','METHOD:REQUEST'])assert.ok(!text.includes(hidden));assert.ok(text.includes('CLASS:PRIVATE'));}],
 ['日历文本转义阻止换行注入，并按 UTF-8 字节折行',()=>{const text=C.calendar({...base,detail:'中文,分号;反斜杠\\\nBEGIN:VEVENT\n'+'陪朋友🌙'.repeat(22)},'test-event',now);for(const line of text.split('\r\n'))assert.ok(Buffer.byteLength(line,'utf8')<=75);const unfolded=text.replace(/\r\n /g,'');assert.equal((unfolded.match(/\r\nBEGIN:VEVENT\r\n/g)||[]).length,1);assert.ok(unfolded.includes('中文\\,分号\\;反斜杠\\\\\\nBEGIN:VEVENT'));assert.throws(()=>C.calendar(base,'bad\r\nUID:injected',now));}],
 ['本机约定只保留白名单字段，损坏记录拒绝读取',()=>{const safe=C.plan({...base,person:'昵称',source:'原话',draft:'草稿',apiKey:'secret'});assert.deepEqual(Object.keys(safe).sort(),Object.keys(C.planDefaults()).sort());assert.equal(C.parseSaved(JSON.stringify(safe)).person,'昵称');assert.equal(C.parseSaved(null),null);for(const broken of ['{bad','[]','{}',JSON.stringify({...safe,at:'oops'}),JSON.stringify({...safe,version:2}),JSON.stringify({...safe,done:true,confirmed:false})])assert.throws(()=>C.parseSaved(broken));}],
 ['独立静态项目不依赖 EchoGlow 文件或远程脚本',()=>{const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8'),app=fs.readFileSync(path.join(__dirname,'app.js'),'utf8');assert.ok(!/src=["'](?:https?:|\.\.\/)/.test(html));assert.ok(!/\.innerHTML\s*=|insertAdjacentHTML\s*\(/.test(app));assert.ok(!/XMLHttpRequest|WebSocket/.test(app));assert.ok(app.includes("KEY='zaichang_plan_v1'"));assert.ok(!app.includes('echoglow_canvas_moments_v1'));}]
];
for(const [label,check]of checks){check();console.log('PASS '+label);}console.log(checks.length+' checks passed.');
